target-version = "py312"
line-length = 140
indent-width = 4

[lint]
select = ["E", "F", "B", "I"]
ignore = []

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

[lint.per-file-ignores]
"__init__.py" = ["F401"]
"lib/migrations/*" = ["E501"]
"lib/models/__init__.py" = ["I001"]

[format]
exclude = [
  "lib/migrations/*"
]
